PROGRAM = callm
CC = gcc
BUILD_DIR ?= cmake-build-debug

all: run

# Clean up the project and remove temporary compilation generated files
cleanup:
	@rm -f *.o *.a *.so *.s *.i
	@rm -f graph.dot*
.PHONY: cleanup

# Remove all the files generated by the build
clear:
	@rm -rf build
	@mkdir build
.PHONY: clear

# Draw the dependency graph
dependency:
	@rm -f graph.dot*
	@cmake -B ./build -S . --graphviz=graph.dot && dot -Tpng graph.dot -o graph.png
.PHONY: dependency

# Generate the documentation
docs:
	@cd docs && doxygen
.PHONY: docs

# Rebuild the project if necessary
build-dev: clear
	@cmake -B ./build -S . -DRELEASE_TYPE=DEV -DLOG_LEVEL=DEBUG
	@cd build && make
.PHONY: build-dev

build-python: clear
	@cmake -B ./build -S . -DRELEASE_TYPE=PYTHON -DLOG_LEVEL=DEBUG
	@cd build && make

# run the project (needs to be built first)
run:
	@cd build && make
	@./build/src/main/callm
.PHONY: run

# Build the safeparser CLI target
build-safeparser:
	@cmake --build $(BUILD_DIR) --target safeparser
	@cp ./cmake-build-debug/src/safeparser/safeparser ./bins/safeparser
.PHONY: build-safeparser

# Build and run safeparser unit tests
test-safeparser:
	@cmake --build $(BUILD_DIR) --target safeparser callm_test_safeparser_query_options callm_test_safeparser_filtering callm_test_safeparser_sorting
	@ctest --test-dir $(BUILD_DIR) --output-on-failure -R "safeparser_(query_options|filtering|sorting)"
.PHONY: test-safeparser

# Run the tests (needs to be built as devfirst)
test:
	@cd build && make
	@cd build/tests && ctest --output-on-failure
.PHONY: test
