PROGRAM = callm
CC = gcc

all: run

# Clean up the project and remove temporary compilation generated files
cleanup:
	@rm -f *.o *.a *.so *.s *.i
	@rm -f graph.dot*
.PHONY: cleanup

# Remove all the files generated by the build
clear:
	@rm -rf build
	@mkdir build
.PHONY: clear

# Draw the dependency graph
dependency:
	@rm -f graph.dot*
	@cmake -B ./build -S . --graphviz=graph.dot && dot -Tpng graph.dot -o graph.png
.PHONY: dependency

# Generate the documentation
docs:
	@cd docs && doxygen
.PHONY: docs

# Rebuild the project if necessary
build-dev: clear
	@cmake -B ./build -S . -DRELEASE_TYPE=DEV -DLOG_LEVEL=DEBUG
	@cd build && make
.PHONY: build-dev

build-python: clear
	@cmake -B ./build -S . -DRELEASE_TYPE=PYTHON -DLOG_LEVEL=DEBUG
	@cd build && make

# run the project (needs to be built first)
run:
	@cd build && make
	@./build/src/main/callm
.PHONY: run

# Run the tests (needs to be built as devfirst)
test:
	@cd build && make
	@cd build/tests && ctest --output-on-failure
.PHONY: test
